[package]
name = "rubicv-example"
version = "0.1.0"
edition = "2021"

[workspace]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
strip = true

[dependencies]
rubicv-sdk = {path = "../rubicv-sdk"}
